import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ProviderProductos } from "./Providers/ProviderProductos";
import { usePathname } from 'next/navigation';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body style={{display:"flex"}}  className={inter.className}>
      <ProviderProductos>
      <div id="header-vertical" className="bg-muted border-r">
            <nav id="nav-header-vertical" className="flex flex-col">
            <Link href="/">
              <div id="item-header-vertical">
              Inicio
              </div>
              </Link>
              <Link href="/sobreNosotros">
             <div id="item-header-vertical">
             nosotros
             </div >
              </Link>
              <Link href="/perfil">
              <div id="item-header-vertical">
              perfil
              </div>
              </Link>
            </nav>
          </div>
          
        {children}
        </ProviderProductos>
        </body>
    </html>
  );
}
